export const demoProducts = [
  {
    sku: "NK-AIR-001",
    name: "Nike Air Max Plus III",
    description: "Responsive cushioning and all-day support.",
    category: "men" as const,
    collection: "summer" as const,
    isTrending: true,
    priceCents: 18000,
    currency: "USD",
    imageUrl: "/images/product-1.jpg",
    stock: 12,
    sizes: ["6", "7", "8", "9", "10", "11", "12"],
    colors: ["Black", "White", "Navy"],
    isActive: true,
  },
  {
    sku: "NK-ZOOM-002",
    name: "Nike Zoom Street Pro",
    description: "Classic design with modern comfort.",
    category: "women" as const,
    collection: "summer" as const,
    isTrending: true,
    priceCents: 16500,
    currency: "USD",
    imageUrl: "/images/product-2.jpg",
    stock: 10,
    sizes: ["6", "7", "8", "9", "10", "11"],
    colors: ["White", "Red"],
    isActive: true,
  },
  {
    sku: "NK-REACT-003",
    name: "Nike React Winter Run",
    description: "Stable cushioned ride for cold-weather runs.",
    category: "men" as const,
    collection: "winter" as const,
    isTrending: false,
    priceCents: 19500,
    currency: "USD",
    imageUrl: "/images/product-3.jpg",
    stock: 7,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["Navy", "Grey"],
    isActive: true,
  },
  {
    sku: "NK-MOTION-004",
    name: "Nike Motion Lite",
    description: "Lightweight comfort and sleek styling.",
    category: "women" as const,
    collection: "autumn" as const,
    isTrending: true,
    priceCents: 15000,
    currency: "USD",
    imageUrl: "/images/product-1.jpg",
    stock: 9,
    sizes: ["5", "6", "7", "8", "9", "10"],
    colors: ["Pearl", "Sand"],
    isActive: true,
  },
  {
    sku: "NK-COURT-005",
    name: "Nike Court Edge",
    description: "Street-ready silhouette and durable traction.",
    category: "men" as const,
    collection: "autumn" as const,
    isTrending: true,
    priceCents: 17200,
    currency: "USD",
    imageUrl: "/images/product-2.jpg",
    stock: 8,
    sizes: ["7", "8", "9", "10", "11", "12", "13"],
    colors: ["Black", "Volt"],
    isActive: true,
  },
  {
    sku: "NK-FLEX-006",
    name: "Nike Flex Aura",
    description: "Soft flex platform for travel and daily wear.",
    category: "women" as const,
    collection: "winter" as const,
    isTrending: false,
    priceCents: 15800,
    currency: "USD",
    imageUrl: "/images/product-3.jpg",
    stock: 11,
    sizes: ["5", "6", "7", "8", "9", "10", "11"],
    colors: ["Rose", "White"],
    isActive: true,
  },
]
